highlighter: rouge
permalink: ./:title
title: "Toolkit"
description: "// Hopefully helpful Tools"
author: "thechelsuk"
url: https://tools.thechels.uk
copyright: "thechelsuk"

owner:
  name: "thechelsuk"
  email: "feedback@thechels.uk"
  url: "https://thechels.uk/about"
  avatar: "https://thechels.uk/.well-known/avatar.png"
  sameAs:
    - "https://reddit.com/user/thechelsuk"
    - "https://youtube.com/thechelsuk"
    - "https://bsky.app/profile/thechels.uk"
    - "https://twitch.tv/thechelsuk"
    - "https://github.com/thechelsuk"
    - "https://keybase.io/thechelsuk"
  jobTitle: "Owner"
  worksFor: "thechelsuk"
organization:
  name: "thechelsuk"
  url: "https://thechels.uk"
  logo: "https://thechels.uk/.well-known/avatar.png"
  sameAs:
    - "https://reddit.com/user/thechelsuk"
    - "https://youtube.com/thechelsuk"
    - "https://bsky.app/profile/thechels.uk"
    - "https://twitch.tv/thechelsuk"
    - "https://github.com/thechelsuk"
    - "https://keybase.io/thechelsuk"


encoding: UTF-8
timezone: Europe/London
future: false
port: 2000
theme:
repository: thechelsuk/uk.thechels.tools
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/thechelsuk/uk.thechels.tools
  branch: main
sass:
  style: compressed
collections:
  bookmarks:
    permalink: /links/:title/
    output: true
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - link: "https://thechels.uk/"
    name: "thechelsuk ⇗"
  - link: "https://links.thechels.uk/"
    name: "Links ⇗"
  - link: "https://cheltenham-od.uk/"
    name: "Cheltenham Open Data ⇗"
  - link: "https://nuchronic.uk/"
    name: "Nuchronic Webring ⇗"
  - link: "https://hiyd.uk/"
    name: "Hiyd ⇗"
  - link: "https://apps.apple.com/gb/developer/mat-benfield/id1818791310"
    name: "AppStore ⇗"
